version: '3.9'

volumes:
  postgres-data:
    driver: local

services:
  #
  # Postgres database
  #
  postgres:
    container_name: postgres
    logging:
      options:
        max-size: '10m'
        max-file: '5'
    ports:
      - 5432:5432
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: super.secret.password.do.not.leak
    volumes:
      - postgres-data:/var/lib/postgresql/data
    image: postgres:alpine
